"""empty message

Revision ID: 2fd8c660e24a
Revises: bc7c8f777c8b
Create Date: 2020-08-03 14:54:09.488324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fd8c660e24a'
down_revision = 'bc7c8f777c8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('referat', sa.Column('wydzial_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'referat', 'wydzial', ['wydzial_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'referat', type_='foreignkey')
    op.drop_column('referat', 'wydzial_id')
    # ### end Alembic commands ###
