"""empty message

Revision ID: bc7c8f777c8b
Revises: ff98bcb8fda6
Create Date: 2020-07-17 15:24:21.903140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc7c8f777c8b'
down_revision = 'ff98bcb8fda6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urzednik', sa.Column('opis', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('urzednik', 'opis')
    # ### end Alembic commands ###
