"""empty message

Revision ID: ff98bcb8fda6
Revises: 8cd99ab49687
Create Date: 2020-07-17 15:03:20.781743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff98bcb8fda6'
down_revision = '8cd99ab49687'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('urzednik',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imie', sa.String(length=20), nullable=True),
    sa.Column('nazwisko', sa.String(length=60), nullable=True),
    sa.Column('user_kolej', sa.Integer(), nullable=True),
    sa.Column('pokoj', sa.String(length=10), nullable=True),
    sa.Column('tel_wew', sa.Integer(), nullable=True),
    sa.Column('telefon', sa.Integer(), nullable=True),
    sa.Column('fax', sa.Integer(), nullable=True),
    sa.Column('stanowisko', sa.String(length=25), nullable=True),
    sa.Column('referat_id', sa.Integer(), nullable=True),
    sa.Column('wydzial_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['referat_id'], ['referat.id'], ),
    sa.ForeignKeyConstraint(['wydzial_id'], ['wydzial.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('urzednik')
    # ### end Alembic commands ###
