# Generated by Django 4.0.1 on 2022-01-17 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Naglowek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dzielnica', models.CharField(max_length=200)),
                ('text_alt', models.CharField(max_length=200)),
                ('wielkosc', models.CharField(choices=[('XL', 'Bardzo Duży'), ('L', 'Duży'), ('M', 'Średni'), ('S', 'Mały'), ('XS', 'Bardzo Mały')], default='XL', max_length=20)),
            ],
        ),
    ]
