# Generated by Django 4.0.1 on 2022-01-20 13:50

import ckeditor.fields
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_alter_naglowek_dzielnica_alter_naglowek_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nazwa', models.CharField(max_length=200)),
                ('Plik', models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(location='info/static/move'), upload_to='')),
                ('Text', ckeditor.fields.RichTextField()),
                ('Kolor', models.CharField(default='#FFFFFF', max_length=200)),
                ('Wielkosc', models.CharField(choices=[('XL', 'Bardzo Duży'), ('L', 'Duży'), ('M', 'Średni'), ('S', 'Mały'), ('XS', 'Bardzo Mały')], default='XL', max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='naglowek',
            name='Kolor',
            field=models.CharField(default='#FFFFFF', max_length=200),
        ),
        migrations.AddField(
            model_name='naglowek',
            name='Nazwa',
            field=models.CharField(default='domyślny', max_length=200),
        ),
        migrations.AlterField(
            model_name='naglowek',
            name='dzielnica',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='naglowek',
            name='logo',
            field=models.ImageField(null=True, storage=django.core.files.storage.FileSystemStorage(location='info/static/img/logo'), upload_to=''),
        ),
    ]
