# Generated by Django 4.0.1 on 2022-01-21 13:55

import colorfield.fields
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_slider_naglowek_kolor_naglowek_nazwa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='naglowek',
            name='Kolor',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None),
        ),
        migrations.AlterField(
            model_name='slider',
            name='Plik',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='info/static/move'), upload_to=''),
        ),
    ]
