# Generated by Django 4.0.1 on 2022-01-24 09:22

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_alter_naglowek_kolor_alter_slider_plik'),
    ]

    operations = [
        migrations.AddField(
            model_name='naglowek',
            name='unike',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='slider',
            name='Kolor',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None),
        ),
    ]
