"""empty message

Revision ID: 8cd99ab49687
Revises: 
Create Date: 2020-07-16 15:40:47.164726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cd99ab49687'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('referat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('referat_krotko', sa.String(length=5), nullable=True),
    sa.Column('referat_pelny', sa.String(length=50), nullable=True),
    sa.Column('referat_kolej', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wydzial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wydzial_krotko', sa.String(length=5), nullable=True),
    sa.Column('wydzial_pelny', sa.String(length=50), nullable=True),
    sa.Column('wydzial_kolej', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wydzial')
    op.drop_table('referat')
    # ### end Alembic commands ###
